import Head from 'next/head'
import Image from 'next/image'
import Script from 'next/script'
import Link from 'next/link'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>my blog</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="keywords" content="nextjs,code for coder" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Script strategy='lazyOnload'>

      </Script>

        <nav className={styles.mainnev}>
          <ul>
           <Link href='/'><a><li>Home</li></a></Link> 
           <Link href='/menu'><a><li>Menu</li></a></Link>
            {/* <Link href='/about'><a><li>About</li></a></Link> */}
            <Link href='/about'><a><li>About</li></a></Link>
            <Link href='/contact'><a><li>Contact</li></a></Link>
          </ul>
        </nav>
      <main className={styles.main}>
        <h1 className={styles.title}>
        New Coder</h1>
        <p className={styles.description}>
         A Blog For Coders By A Coder
        </p>
         
         <div className="blog">
          <div className="blogs">
            <h1>How to learn javascript in 2022</h1>
            <p> javascript is the language used to design logic for the server site</p>
          </div>

          <div className="blogs">
            <h3>How to learn ReactJs in 2022</h3>
            <p> javascript is the language used to design logic for the client site</p>
          </div>

          <div className="blogs">
            <h3>How to learn NodeJs in 2022</h3>
            <p> javascript is the language used to design logic for the server site</p>
          </div>
          
         </div>
        
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
